### ISSUE TITLE
Не работает роутинг на ms-backend

### ISSUE THREAD

**Issue by khanZhomart** [majestic-sprinters/ms-gateway#9]

**Comment by Dumanbruh** [comment]
**Было:**
![image](https://github.com/majestic-sprinters/ms-gateway/assets/74466653/7753211e-5067-4da6-953b-e9766d005c63)
**Стало**
![image](https://github.com/majestic-sprinters/ms-gateway/assets/74466653/232c7126-91d6-4b49-b837-02937eb84401)

**Comment by khanZhomart** [comment]
пон
